<a href='https://www.hexnbit.com/'> <img src='hexnbit.png'/> </a>

# A1_Assignment

Mentioned below are the tasks, the solution for each tasks has to be appended by inserting a new cell below the task,
along with the following description:-
1. Why the method was used (if applicable)
2. Explanation of logic

### Task1

- Convert all characters of the word "PYTHON" to its decimal equivalent and then store them.
- Convert all the decimal equvalents back to characters 

**Hint:** Built in functions to do so are there to perform this task
Refer https://docs.python.org/3/library/functions.html

In [4]:
a="PYTHON"
b=[]             # the array b[] is used to store the decimal equivalents of the corresponding letters in str
c=""
for i in a:      # here i refers to each letter in the string "a"
    b.append(ord(i))      #ord() is a built-in function which will convert the character into decimal equivalent.
print(b)
for i in b:               # converting decimals to characters
    c=c + chr(i)          # chr() function is opposite to ord(), We are appending each converted decimal(char) to the empty str "c"
print(c)
    

[80, 89, 84, 72, 79, 78]
PYTHON


### Task2
- Raise 2 to the power 10

In [5]:
print(2**10)   # ** is used to raise the power of a number.

1024


### Task3

- From the given list, starting from Japan, print alternate elements
- From the given list, print element at indexes 1,4,5,8 (**Hint**: Use for loop or list comprehension)

In [7]:
# Task 3
list1=["India", "Japan","Singapore","China","Australia","Africa","Dubai","France","Italy","Germany"]

In [8]:
print(list1[::2])  # Slicing is the easiest way to perform the operations like this. slice[x:y:z], here x refers to the 
                   #starting index,y refers to ending index+1, z refers to increment.if we haven't given x,y it will take 0,len(list1) respectively.

['India', 'Singapore', 'Australia', 'Dubai', 'Italy']


In [9]:
for i in [1,4,5,8]:  # here i refers to 1 in loop1, 4 in loop2 and so on.
    print(list1[i])

Japan
Australia
Africa
Italy


### Task4

- From the given list, extract the "Hex" and print it

In [10]:
# Task 4
list2=[22,[4, [True, False], 6, 8], [888, 999,[111,222,["Hex"]]] ]

In [11]:
# hex is the third element in list2(index=2),so we used list[2],but list[2] is again a list and 
#hex is at index 2 so list[2][2], and list[2][2] is also a list in which hex is at index 2,
#so it is list[2][2][2], this list[2][2][2] is a list with one element hex, so list[2][2][2][0] is our destination.
p=list2[2][2][2][0]  
print(p)

Hex


### Task5

- From the given dictionary, fetch the keyword "TOPD"

In [12]:
# Task 5
dict1={"Tevatron":["Technologies","Pvt","Ltd",{"Domains":["Embedded","IoT","AI","ML"],"Projects":["inhouse","TOPD"]}]}

In [14]:
# We are using the same traversing technique we have done in task 4.
f=dict1["Tevatron"][3]["Projects"][1]
print(f)

TOPD


### Task6
There are 3 height categories

**167 and below  =**    Short <br>
**168 to 182     =**    Average <br>
**182 and above  =**    Tall<br>

Write a programe which gets the input from user and prints if the category the person fits in

**Hint**: Use function input()

In [20]:
height=int(input())
if height>0 and height<=167:
    print("Short")
elif height>167 and height<182:
    print("Average")
elif height>=182:
    print("Tall")

150
Short


### Task7

Using maximum 2 lines of code, generate all upper case alphabets

**Hint**: Refer ASCII Table

In [21]:
for i in range(65,91):# Decimal value of A is 65 and Z is 90.
    print(chr(i))     #chr() will convert decimal value to character.

A
B
C
D
E
F
G
H
I
J
K
L
M
N
O
P
Q
R
S
T
U
V
W
X
Y
Z


### Task8

Generate integers between (100 and 200) both inclusive, using NumPy

In [3]:
import numpy as np
arr=np.arange(100,201) # arange() will create integers based on the range given and store it in a 1-D array
print(arr)

[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153
 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171
 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189
 190 191 192 193 194 195 196 197 198 199 200]


### Task9

Print all even integers from the array created in Task8

In [5]:
list2=(arr%2==0)
print(arr[list2])

[100 102 104 106 108 110 112 114 116 118 120 122 124 126 128 130 132 134
 136 138 140 142 144 146 148 150 152 154 156 158 160 162 164 166 168 170
 172 174 176 178 180 182 184 186 188 190 192 194 196 198 200]


### Task10

Print all 100 values from Standard Normal Distribution

In [31]:
snd=np.random.normal(size=100)
print(snd)

[ 0.48569364 -0.39308713 -1.68784196  0.10008742 -1.21661637  0.34436706
 -0.88641331  1.8046806   1.17608354  0.02815647 -1.25360155  1.55918813
  3.4798274   1.32901567  0.34245991 -0.12273196 -0.89464144  0.98289363
  0.14445968 -0.00619162 -0.86007331  0.16608182 -0.24549833  0.12940477
 -0.37758064 -0.79650152  0.15206596  0.00394492  0.05721532  0.05911468
 -1.22505346 -0.14240714 -0.06482656 -0.77249761 -0.31887774  1.69003548
 -0.52266078  0.03949852  0.3567293   0.98670153 -0.45331305  0.39122591
 -2.64299024  0.65871236 -0.49123042 -0.05534916 -0.87961357 -2.34395657
  1.29470695 -1.90057671 -0.21593063 -0.71644064 -0.22891664 -0.52060325
 -0.80305744  0.06366419  0.73172269  0.04379892  1.12186557 -0.22050021
 -0.79208285 -0.17161721  0.60720476  0.85914851 -0.6836303  -0.82000864
 -0.10529476  0.1953116   0.33102725 -0.09989016 -0.50664025  1.89913956
 -0.92328167  0.08771962 -1.2254899   0.4754441   0.78635973 -2.65787156
 -1.1990609   0.99806814 -0.65978875  0.23765359  0

### Task11

Create a NumPy array of random number, whose dimension attribute is equal to 4

In [12]:
arr1=np.random.randint(1,50,81).reshape(3,3,3,3) #3^4 is 81 so we used 81 as the no.of elements.
print(arr1)
print(arr1.ndim)# output is 4 as the dimension of matrix is 4.

[[[[ 7 18 25]
   [32 40 43]
   [20 13  3]]

  [[ 5  6 10]
   [45 33  7]
   [23 37 40]]

  [[26 42  2]
   [ 2  1 36]
   [28 31 41]]]


 [[[44 37 14]
   [13 48 45]
   [16 14 10]]

  [[10 19 12]
   [37 32 40]
   [27 40 10]]

  [[27 35  1]
   [39  5  2]
   [ 2 36 34]]]


 [[[10 32 23]
   [15 45  6]
   [45  9 36]]

  [[46 44 16]
   [48  1  2]
   [38  4 13]]

  [[24  2 48]
   [ 6 32 28]
   [39 43 10]]]]
4


### Task12

Create an NumPy array of 100 values evenly spaced between 10 and 20

In [13]:
arr3=np.linspace(10,20,100)
print(arr3)

[10.         10.1010101  10.2020202  10.3030303  10.4040404  10.50505051
 10.60606061 10.70707071 10.80808081 10.90909091 11.01010101 11.11111111
 11.21212121 11.31313131 11.41414141 11.51515152 11.61616162 11.71717172
 11.81818182 11.91919192 12.02020202 12.12121212 12.22222222 12.32323232
 12.42424242 12.52525253 12.62626263 12.72727273 12.82828283 12.92929293
 13.03030303 13.13131313 13.23232323 13.33333333 13.43434343 13.53535354
 13.63636364 13.73737374 13.83838384 13.93939394 14.04040404 14.14141414
 14.24242424 14.34343434 14.44444444 14.54545455 14.64646465 14.74747475
 14.84848485 14.94949495 15.05050505 15.15151515 15.25252525 15.35353535
 15.45454545 15.55555556 15.65656566 15.75757576 15.85858586 15.95959596
 16.06060606 16.16161616 16.26262626 16.36363636 16.46464646 16.56565657
 16.66666667 16.76767677 16.86868687 16.96969697 17.07070707 17.17171717
 17.27272727 17.37373737 17.47474747 17.57575758 17.67676768 17.77777778
 17.87878788 17.97979798 18.08080808 18.18181818 18

### Task13

Create a NumPy array of shape 5x5 and print the last 3 rows

In [33]:
arr4=np.random.randint(1,50,size=(5,5))
print(arr4)
print("\n",arr4[2:5])

[[38 34 25 17 10]
 [43 45  2 27 20]
 [33 31 44 14 27]
 [35 33 26 39  8]
 [23 29 33 32 18]]

 [[33 31 44 14 27]
 [35 33 26 39  8]
 [23 29 33 32 18]]


### Task14

Using the array created above in Task13, Print the first 2 columns

In [17]:
print(arr4[0:2])

[[39 32  8 40 33]
 [41  4 32 23 35]]


### Task15

Create an array of 25 random values
- Find the sum of all elements
- Print the element with maximum value and minimum value

In [19]:
arr5=np.random.randint(1,100,25)
print(arr5)
print(arr5.sum())
print(arr5.max())
print(arr5.min())

[ 1  8 54 49 93  1 16 66 59 32 69 38 15 75 76 56 12  2 55 91 22 89 13 69
 61]
1122
93
1


### Task16

In the array created above, print columns with indexes 1,3,4 without directly indexing them <br>
**Hint:** Make use of another list for indexing

In [30]:
l1=[1,3,4]
print(arr5[l1])

[ 8 49 93]


### Task17
Read car_sales.csv

In [19]:
import pandas as pd
car_data=pd.read_csv("car_sales.csv")


In [20]:
car_data


Unnamed: 0 Manufacturer    Model     Type  Min.Price  Price  Max.Price  \
0            1        Acura  Integra    Small       12.9   15.9       18.8   
1            2        Acura   Legend  Midsize       29.2   33.9       38.7   
2            3         Audi       90  Compact       25.9   29.1       32.3   
3            4         Audi      100  Midsize       30.8   37.7       44.6   
4            5          BMW     535i  Midsize       23.7   30.0       36.2   
..         ...          ...      ...      ...        ...    ...        ...   
88          89   Volkswagen  Eurovan      Van       16.6   19.7       22.7   
89          90   Volkswagen   Passat  Compact       17.6   20.0       22.4   
90          91   Volkswagen  Corrado   Sporty       22.9   23.3       23.7   
91          92        Volvo      240  Compact       21.8   22.7       23.5   
92          93        Volvo      850  Midsize       24.8   26.7       28.5   

    MPG.city  MPG.highway             AirBags  ... Passengers Length  \
0         25           31                None  ...          5    177   
1         18           25  Driver & Passenger  ...          5    195   
2         20           26         Driver only  ...          5    180   
3         19           26  Driver & Passenger  ...          6    193   
4         22           30         Driver only  ...          4    186   
..       ...          ...                 ...  ...        ...    ...   
88        17           21                None  ...          7    187   
89        21           30                None  ...          5    180   
90        18           25                None  ...          4    159   
91        21           28         Driver only  ...          5    190   
92        20           28  Driver & Passenger  ...          5    184   

    Wheelbase  Width  Turn.circle  Rear.seat.room Luggage.room  Weight  \
0         102     68           37            26.5         11.0    2705   
1         115     71           38            30.0         15.0    3560   
2         102     67           37            28.0         14.0    3375   
3         106     70           37            31.0         17.0    3405   
4         109     69           39            27.0         13.0    3640   
..        ...    ...          ...             ...          ...     ...   
88        115     72           38            34.0          NaN    3960   
89        103     67           35            31.5         14.0    2985   
90         97     66           36            26.0         15.0    2810   
91        104     67           37            29.5         14.0    2985   
92        105     69           38            30.0         15.0    3245   

     Origin                Make  
0   non-USA       Acura Integra  
1   non-USA        Acura Legend  
2   non-USA             Audi 90  
3   non-USA            Audi 100  
4   non-USA            BMW 535i  
..      ...                 ...  
88  non-USA  Volkswagen Eurovan  
89  non-USA   Volkswagen Passat  
90  non-USA  Volkswagen Corrado  
91  non-USA           Volvo 240  
92  non-USA           Volvo 850  

[93 rows x 28 columns]

### Task18
Sort data frame in ascending order of the Price column

In [40]:
car_data.sort_values("Price")

Unnamed: 0   Manufacturer     Model     Type  Min.Price  Price  Max.Price  \
30          31           Ford   Festiva    Small        6.9    7.4        7.9   
43          44        Hyundai     Excel    Small        6.8    8.0        9.2   
52          53          Mazda       323    Small        7.4    8.3        9.1   
38          39            Geo     Metro    Small        6.7    8.4       10.0   
79          80         Subaru     Justy    Small        7.3    8.4        9.5   
..         ...            ...       ...      ...        ...    ...        ...   
3            4           Audi       100  Midsize       30.8   37.7       44.6   
18          19      Chevrolet  Corvette   Sporty       34.6   38.0       41.5   
10          11       Cadillac   Seville  Midsize       37.5   40.1       42.7   
47          48       Infiniti       Q45  Midsize       45.4   47.9       50.4   
58          59  Mercedes-Benz      300E  Midsize       43.8   61.9       80.0   

    MPG.city  MPG.highway             AirBags  ... Passengers Length  \
30        31           33                None  ...          4    141   
43        29           33                None  ...          5    168   
52        29           37                None  ...          4    164   
38        46           50                None  ...          4    151   
79        33           37                None  ...          4    146   
..       ...          ...                 ...  ...        ...    ...   
3         19           26  Driver & Passenger  ...          6    193   
18        17           25         Driver only  ...          2    179   
10        16           25  Driver & Passenger  ...          5    204   
47        17           22         Driver only  ...          5    200   
58        19           25  Driver & Passenger  ...          5    187   

    Wheelbase  Width  Turn.circle  Rear.seat.room Luggage.room  Weight  \
30         90     63           33            26.0         12.0    1845   
43         94     63           35            26.0         11.0    2345   
52         97     66           34            27.0         16.0    2325   
38         93     63           34            27.5         10.0    1695   
79         90     60           32            23.5         10.0    2045   
..        ...    ...          ...             ...          ...     ...   
3         106     70           37            31.0         17.0    3405   
18         96     74           43             NaN          NaN    3380   
10        111     74           44            31.0         14.0    3935   
47        113     72           42            29.0         15.0    4000   
58        110     69           37            27.0         15.0    3525   

     Origin                Make  
30      USA        Ford Festiva  
43  non-USA       Hyundai Excel  
52  non-USA           Mazda 323  
38  non-USA           Geo Metro  
79  non-USA        Subaru Justy  
..      ...                 ...  
3   non-USA            Audi 100  
18      USA  Chevrolet Corvette  
10      USA    Cadillac Seville  
47  non-USA        Infiniti Q45  
58  non-USA  Mercedes-Benz 300E  

[93 rows x 28 columns]

### Task19
Print number of unique car manufacturers in the data

In [34]:
print(car_data["Manufacturer"].unique())

['Acura' 'Audi' 'BMW' 'Buick' 'Cadillac' 'Chevrolet' 'Chrylser' 'Chrysler'
 'Dodge' 'Eagle' 'Ford' 'Geo' 'Honda' 'Hyundai' 'Infiniti' 'Lexus'
 'Lincoln' 'Mazda' 'Mercedes-Benz' 'Mercury' 'Mitsubishi' 'Nissan'
 'Oldsmobile' 'Plymouth' 'Pontiac' 'Saab' 'Saturn' 'Subaru' 'Suzuki'
 'Toyota' 'Volkswagen' 'Volvo']


### Task20
Print the maximum Wheelbase from the data

In [22]:
car_data["Wheelbase"].max()

119

### Task21
Print the car Model which has maximum Wheelbase

In [24]:
m=car_data[car_data["Wheelbase"]==car_data["Wheelbase"].max()]["Model"]
print(m)

35    Aerostar
Name: Model, dtype: object


### Task22

Print the Details of car with maximum passenger capacity

In [31]:
k=car_data[car_data["Passengers"]==car_data["Passengers"].max()]


In [32]:
k

Unnamed: 0 Manufacturer  Model Type  Min.Price  Price  Max.Price  \
16          17    Chevrolet  Astro  Van       14.7   16.6       18.6   

    MPG.city  MPG.highway AirBags  ... Passengers Length  Wheelbase  Width  \
16        15           20    None  ...          8    194        111     78   

    Turn.circle  Rear.seat.room Luggage.room  Weight  Origin             Make  
16           42            33.5          NaN    4025     USA  Chevrolet Astro  

[1 rows x 28 columns]